# Generated by Django 5.2.4 on 2026-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.SlugField(
                blank=True,
                help_text="Your unique profile URL (no spaces, letters/numbers only)",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
    ]
