"""
Django settings for modmixx project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from env.py if it exists
# This allows for sensitive information to be kept out of version control
if os.path.exists(os.path.join(BASE_DIR, "env.py")):
    import env  # noqa: F401


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG") == "True"

# Parse ALLOWED_HOSTS from environment variable
allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",")]

# SSL/Security settings - environment specific
if DEBUG:
    # Development settings - no SSL redirect
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None
else:
    # Production settings - force enable SSL
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for django-allauth
    "allauth",  # Django Allauth for authentication
    "allauth.account",  # Django Allauth for account management
    "allauth.socialaccount",  # Django Allauth for social accounts
    "allauth.socialaccount.providers.google",  # Google provider for Allauth
    "accounts",  # Custom app for user accounts
    "core",  # Core app for generic views like home page, etc.
    "tracks",  # App for managing tracks
    "crispy_forms",  # For crispy forms
    "crispy_bootstrap5",  # For Bootstrap 5 styling with crispy forms
    "comments",  # App for managing comments
    "contact",  # App for managing contact forms
    "storages",  # For AWS S3 storage
    "captcha",  # For reCAPTCHA integration in forms
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # For serving static files
]

ROOT_URLCONF = "modmixx.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

WSGI_APPLICATION = "modmixx.wsgi.application"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": dj_database_url.parse(os.environ.get("DATABASE_URL"))}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]

# Custom User Model
AUTH_USER_MODEL = "accounts.CustomUser"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary static files directory
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = (
    BASE_DIR / "staticfiles"
)  # For production static files collection

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY"),
            "secret": os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET"),
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
            # Forces both account picker and consent
            "prompt": "select_account consent",
        },
        "VERIFIED_EMAIL": True,
    }
}

# Django Allauth Configuration
# Implements email-based authentication with Google OAuth integration
# Configured for sheltered community approach (members-only content)
# Environment-specific SITE_ID
SITE_ID = int(os.environ.get("SITE_ID", "2"))  # Default to 2 for production

# Current Allauth 65+ settings format
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"  # Disabled for development
ACCOUNT_ALLOW_REGISTRATION = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True

# allauth-specific logout settings:
ACCOUNT_LOGOUT_REDIRECT_URL = "/"  # For allauth logout
ACCOUNT_LOGOUT_ON_GET = True  # Allow GET logout from allauth pages
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = (
    False  # Don't auto-logout on password change
)

# Custom user model compatibility
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Use email as the unique identifier
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"

# Redirect configuration for sheltered community
LOGIN_REDIRECT_URL = "/login-redirect/"  # Authenticated users see track feed
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/login/"  # Redirect to login page for unauthenticated users

SOCIALACCOUNT_STORE_TOKENS = False

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# AWS S3 Storage
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = "modmixx-v2-media"
AWS_S3_REGION_NAME = "eu-west-2"
AWS_S3_CUSTOM_DOMAIN = (
    f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
)

# AWS S3 settings
AWS_DEFAULT_ACL = ""
AWS_QUERYSTRING_AUTH = False  # Clean public URLs

# Use S3 for all media files
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# URL for accessing media files
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

# Django 5 storage config
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Content Moderation Settings
# Perspective API 
PERSPECTIVE_API_KEY = os.environ.get("PERSPECTIVE_API_KEY")


# Rekognition config
AWS_REGION = os.environ.get("AWS_REGION", "eu-west-1")
IMAGE_MODERATION_ENABLED = (
    os.environ.get("IMAGE_MODERATION_ENABLED", "true").lower() == "true"
)
REKOG_MIN_CONFIDENCE = int(os.environ.get("REKOG_MIN_CONFIDENCE", "80"))

# Rekognition credentials
REKOGNITION_ACCESS_KEY = os.environ.get("REKOGNITION_ACCESS_KEY")
REKOGNITION_SECRET = os.environ.get("REKOGNITION_SECRET")

# reCAPTCHA keys
RECAPTCHA_PUBLIC_KEY = os.environ.get("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = os.environ.get("RECAPTCHA_PRIVATE_KEY")